package com.mazhar.jarvis;
import org.json.*;import okhttp3.*;import android.content.*;import android.provider.MediaStore;import android.net.Uri;import java.io.*;import java.util.zip.*;
final class GitBuild {
 static final String ROOT="https://api.github.com/repos/";
 static void validate(String repo)throws Exception{if(!repo.matches("[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"))throw new Exception("Repository must be owner/name");}
 static Request.Builder request(String url,String key){return new Request.Builder().url(url).header("Authorization","Bearer "+key).header("Accept","application/vnd.github+json").header("X-GitHub-Api-Version","2022-11-28");}
 static String json(String url,String token,String body)throws Exception{Request.Builder b=request(url,token);if(body!=null)b.post(RequestBody.create(body,MediaType.get("application/json")));try(Response r=Ai.HTTP.newCall(b.build()).execute()){if(!r.isSuccessful())throw new Exception("GitHub HTTP "+r.code()+". Check repository, token permissions and installed workflow.");return r.body().string();}}
 static String start(String repo,String key,String name,String pkg,String html)throws Exception{validate(repo);if(!pkg.matches("[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*){2,}"))throw new Exception("Use a package ID like com.mazhar.myapp");String data=android.util.Base64.encodeToString(html.getBytes(java.nio.charset.StandardCharsets.UTF_8),2);if(data.length()>60000)throw new Exception("This build route supports HTML up to 45 KB. Export a larger project to Universal Build Studio.");String ticket=java.util.UUID.randomUUID().toString();json(ROOT+repo+"/actions/workflows/jarvis-project.yml/dispatches",key,Ai.obj("ref","main","inputs",Ai.obj("html",data,"name",name,"package",pkg,"ticket",ticket)).toString());return ticket;}
 static void check(Context c,String repo,String key,String ticket)throws Exception{validate(repo);JSONArray runs=new JSONObject(json(ROOT+repo+"/actions/workflows/jarvis-project.yml/runs?event=workflow_dispatch&per_page=50",key,null)).getJSONArray("workflow_runs");JSONObject run=null;for(int i=0;i<runs.length();i++)if(runs.getJSONObject(i).optString("display_title").equals("Jarvis app "+ticket))run=runs.getJSONObject(i);if(run==null)throw new Exception("Build queued or no longer in recent runs; check GitHub Actions");if(!run.optString("status").equals("completed"))throw new Exception("Build is "+run.optString("status")+". Check again shortly.");if(!run.optString("conclusion").equals("success"))throw new Exception("Build failed; view the GitHub Actions log to diagnose it.");JSONArray artifacts=new JSONObject(json(ROOT+repo+"/actions/runs/"+run.getLong("id")+"/artifacts",key,null)).getJSONArray("artifacts");JSONObject artifact=null;for(int i=0;i<artifacts.length();i++)if(artifacts.getJSONObject(i).getString("name").equals("generated-apk"))artifact=artifacts.getJSONObject(i);if(artifact==null||artifact.optBoolean("expired"))throw new Exception("APK artifact is not available or expired");String url=ROOT+repo+"/actions/artifacts/"+artifact.getLong("id")+"/zip";Response response=Ai.HTTP.newCall(request(url,key).build()).execute();
  if(response.code()==302){String location=response.header("Location");response.close();HttpUrl parsed=HttpUrl.parse(location==null?"":location);if(parsed==null||!parsed.isHttps())throw new Exception("Invalid artifact redirect");response=Ai.HTTP.newCall(new Request.Builder().url(parsed).build()).execute();}
  try(Response r=response){if(!r.isSuccessful())throw new Exception("Could not download APK archive");try(ZipInputStream z=new ZipInputStream(r.body().byteStream())){ZipEntry entry;while((entry=z.getNextEntry())!=null){if(!entry.isDirectory()&&entry.getName().endsWith(".apk")){ContentValues values=new ContentValues();values.put(MediaStore.MediaColumns.DISPLAY_NAME,"Jarvis-"+ticket.substring(0,8)+".apk");values.put(MediaStore.MediaColumns.MIME_TYPE,"application/vnd.android.package-archive");values.put(MediaStore.MediaColumns.RELATIVE_PATH,"Download/Jarvis");values.put(MediaStore.MediaColumns.IS_PENDING,1);Uri uri=c.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values);if(uri==null)throw new Exception("Could not save APK");try{try(OutputStream out=c.getContentResolver().openOutputStream(uri)){byte[] b=new byte[8192];int n;long size=0;while((n=z.read(b))!=-1){size+=n;if(size>100*1024*1024)throw new Exception("APK exceeds size limit");out.write(b,0,n);}}values.clear();values.put(MediaStore.MediaColumns.IS_PENDING,0);c.getContentResolver().update(uri,values,null,null);return;}catch(Exception e){c.getContentResolver().delete(uri,null,null);throw e;}}}throw new Exception("No APK in build archive");}}
 }
}
