package com.mazhar.jarvis;
import android.content.*;import android.net.Uri;import android.provider.MediaStore;import org.json.*;import okhttp3.*;import java.io.*;
final class Images {
 static Uri create(Context c,JSONObject p,String model,String prompt)throws Exception {
  String base=Ai.endpoint(p),type=p.optString("type");JSONObject body;String url;Request.Builder request=new Request.Builder();
  if(!model.matches("[a-zA-Z0-9_.:-]+"))throw new Exception("Enter the provider's image model ID");
  if(type.equals("gemini")){url=base+"/models/"+model+":generateContent";body=Ai.obj("contents",new JSONArray().put(Ai.obj("parts",new JSONArray().put(Ai.obj("text",prompt)))),"generationConfig",Ai.obj("responseModalities",new JSONArray().put("TEXT").put("IMAGE")));request.header("x-goog-api-key",p.getString("key"));}
  else if(type.equals("messages"))throw new Exception("This Messages connection has no image-generation adapter. Select Gemini or an Images API-compatible provider.");
  else{url=base+"/images/generations";body=Ai.obj("model",model,"prompt",prompt,"n",1,"size","1024x1024");request.header("Authorization","Bearer "+p.getString("key"));}
  byte[] bytes=null;String mime="image/png";
  try(Response response=Ai.HTTP.newCall(request.url(url).post(RequestBody.create(body.toString(),MediaType.get("application/json"))).build()).execute()){
   if(!response.isSuccessful())throw new Exception("Image API HTTP "+response.code()+". Check image-model access, credits and endpoint support.");JSONObject data=new JSONObject(response.body().string());
   if(type.equals("gemini")){JSONArray parts=data.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts");for(int i=0;i<parts.length();i++){JSONObject item=parts.getJSONObject(i).optJSONObject("inlineData");if(item!=null){bytes=android.util.Base64.decode(item.getString("data"),0);mime=item.optString("mimeType","image/png");break;}}}
   else{JSONObject item=data.getJSONArray("data").getJSONObject(0);if(item.has("b64_json"))bytes=android.util.Base64.decode(item.getString("b64_json"),0);else if(item.has("url")){HttpUrl image=HttpUrl.parse(item.getString("url"));if(image==null||!image.isHttps())throw new Exception("Image URL must be HTTPS");try(Response r=Ai.HTTP.newCall(new Request.Builder().url(image).build()).execute()){if(!r.isSuccessful())throw new Exception("Image download failed");if(r.body().contentLength()>25*1024*1024)throw new Exception("Image too large");ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=r.body().byteStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>25*1024*1024)throw new Exception("Image too large");out.write(b,0,n);}}bytes=out.toByteArray();mime=r.header("Content-Type","image/png").split(";")[0];}}}
  }
  if(bytes==null||bytes.length==0||bytes.length>25*1024*1024)throw new Exception("No supported image returned");android.graphics.BitmapFactory.Options bounds=new android.graphics.BitmapFactory.Options();bounds.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);if(bounds.outWidth<=0)throw new Exception("Response is not a decodable image");mime=bounds.outMimeType;
  ContentValues v=new ContentValues();v.put(MediaStore.MediaColumns.DISPLAY_NAME,"Jarvis-"+System.currentTimeMillis()+("image/jpeg".equals(mime)?".jpg":"image/webp".equals(mime)?".webp":".png"));v.put(MediaStore.MediaColumns.MIME_TYPE,mime);v.put(MediaStore.MediaColumns.RELATIVE_PATH,"Pictures/Jarvis");v.put(MediaStore.MediaColumns.IS_PENDING,1);Uri uri=c.getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(uri==null)throw new Exception("Cannot save image");try{try(OutputStream out=c.getContentResolver().openOutputStream(uri)){out.write(bytes);}v.clear();v.put(MediaStore.MediaColumns.IS_PENDING,0);c.getContentResolver().update(uri,v,null,null);return uri;}catch(Exception e){c.getContentResolver().delete(uri,null,null);throw e;}
 }
}
