package com.mazhar.jarvis;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.speech.*;import android.speech.tts.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.file.Files;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity implements RecognitionListener {
 final ExecutorService pool=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());
 JSONArray profiles=new JSONArray(),history=new JSONArray();int selected=0;boolean busy=false,calling=false,voiceReady=false,foreground=true;int speechErrors=0;
 SpeechRecognizer speech;TextToSpeech tts;LinearLayout body,chat,agentPanel;TextView status,wave,agentState;EditText input;Button call;Spinner mode;String photo="",project="";String export="";
 final String system="You are Jarvis, an AI work assistant. Speak concise natural Urdu by default; use English for code and listing copy. Do not claim to be human or to have completed tool actions you cannot perform. User runs Clawora Beauty, a cosmetics reseller. Do not invent product ingredients, safety claims, official images or verified facts. Ask for missing details. Never claim an APK was built or a website published by writing text. Your tools here are generating text and a complete self-contained HTML/CSS/JS file for a web-app project. No live web search or Shopify access is connected. Respect privacy and refuse harmful requests.";
 @Override public void onCreate(Bundle state){super.onCreate(state);Thread.setDefaultUncaughtExceptionHandler((thread,error)->{try{getPreferences(0).edit().putString("lastCrash",error.getClass().getSimpleName()+": "+String.valueOf(error.getMessage())).apply();}catch(Throwable ignored){};});try{profiles=new JSONArray(Vault.get(this,"profiles","[]"));history=new JSONArray(Vault.get(this,"history","[]"));selected=getPreferences(0).getInt("selected",0);File f=new File(getFilesDir(),"project.html");if(f.exists())project=Fs.readString(f.toPath());}catch(Exception e){toast("Could not restore saved data: "+e.getMessage());}
 tts=new TextToSpeech(this,result->{if(result==TextToSpeech.SUCCESS){int lang=tts.setLanguage(Locale.forLanguageTag("ur-PK"));voiceReady=lang>=0;if(!voiceReady)toast("Install an Urdu text-to-speech voice in Android settings for spoken replies.");}});
 tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){handler.post(()->{if(calling){if(agentState!=null)agentState.setText("LISTENING · Urdu / Hindi");listenLater();}});}public void onError(String id){handler.post(()->{stopCall();toast("Speech playback failed; check Urdu voice settings");});}});
 home();String crash=getPreferences(0).getString("lastCrash","");if(!crash.isEmpty()){status.setText("Previous run stopped safely: "+crash);getPreferences(0).edit().remove("lastCrash").apply();}}
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
 void toast(String s){runOnUiThread(()->{if(status!=null)status.setText(s);Toast.makeText(this,s,Toast.LENGTH_LONG).show();});}
 TextView label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(0xffeeeeef);t.setPadding(0,dp(8),0,dp(8));return t;}
 Button button(String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(0xff07100a);b.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD);GradientDrawable bg=new GradientDrawable();bg.setColor(0xff55ff88);bg.setCornerRadius(dp(14));b.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);b.setOnClickListener(v->action.run());return b;}
 EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(-1);e.setHintTextColor(0xffaaaab3);e.setSingleLine(true);e.setPadding(dp(10),dp(8),dp(10),dp(8));return e;}
 LinearLayout panel(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(dp(20),dp(12),dp(20),dp(12));return l;}
 void home(){
  ScrollView scroll=new ScrollView(this); body=new LinearLayout(this); body.setOrientation(LinearLayout.VERTICAL); body.setPadding(dp(18),dp(10),dp(18),dp(18)); body.setBackgroundColor(0xff050806); scroll.addView(body); scroll.setFillViewport(true); setContentView(scroll);
  scroll.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom);return insets;});
  LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL);
  TextView title=label("JARVIS",25); title.setTextColor(0xff55ff88); title.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD); top.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));
  Button menu=new Button(this); menu.setText("⋮"); menu.setTextSize(27); menu.setTextColor(0xff55ff88); menu.setBackgroundColor(0x00000000); menu.setOnClickListener(v->quickMenu()); top.addView(menu,new LinearLayout.LayoutParams(dp(54),dp(58))); body.addView(top);
  status=label("●  READY  ·  tap here to connect your AI",12); status.setOnClickListener(v->connections()); status.setTextColor(0xff65d98a); status.setTypeface(android.graphics.Typeface.MONOSPACE); body.addView(status);
  agentPanel=new LinearLayout(this); agentPanel.setOrientation(LinearLayout.VERTICAL); agentPanel.setGravity(Gravity.CENTER_HORIZONTAL); agentPanel.setPadding(0,dp(12),0,dp(12)); agentPanel.setVisibility(View.GONE);
  TextView orb=label("◉",58); orb.setTextColor(0xff55ff88); orb.setGravity(Gravity.CENTER); orb.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD); agentPanel.addView(orb,new LinearLayout.LayoutParams(-1,dp(72)));
  agentState=label("JARVIS CALL MODE",12); agentState.setTextColor(0xff65d98a); agentState.setGravity(Gravity.CENTER); agentState.setTypeface(android.graphics.Typeface.MONOSPACE); agentPanel.addView(agentState);
  wave=label("·  ·  ·  ·  ·",22); wave.setTextColor(0xff55ff88); wave.setGravity(Gravity.CENTER); wave.setTypeface(android.graphics.Typeface.MONOSPACE); agentPanel.addView(wave);
  body.addView(agentPanel); chat=new LinearLayout(this); chat.setOrientation(LinearLayout.VERTICAL); chat.setPadding(dp(2),dp(12),dp(2),dp(8)); body.addView(chat); renderHistory();
  LinearLayout compose=new LinearLayout(this); compose.setOrientation(LinearLayout.VERTICAL); compose.setPadding(0,dp(8),0,0);
  input=field("Message Jarvis…",""); input.setSingleLine(false); input.setMinLines(2); input.setMaxLines(6); input.setTextColor(0xffeffff2); input.setHintTextColor(0xff6c8a74); input.setTextSize(16); GradientDrawable ibg=new GradientDrawable(); ibg.setColor(0xff101b13); ibg.setStroke(dp(1),0xff245d35); ibg.setCornerRadius(dp(16)); input.setBackground(ibg); compose.addView(input,new LinearLayout.LayoutParams(-1,dp(72)));
  LinearLayout actions=new LinearLayout(this); actions.setGravity(Gravity.CENTER); call=button("CALL  ◉",()->{if(calling)stopCall();else startCall();}); call.setTextColor(0xff07100a); call.setTextSize(13); call.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD); Button sendBtn=button("SEND  ➤",()->send(input.getText().toString())); sendBtn.setTextSize(13); sendBtn.setTextColor(0xff07100a); actions.addView(call,new LinearLayout.LayoutParams(0,dp(54),1)); actions.addView(sendBtn,new LinearLayout.LayoutParams(0,dp(54),1)); compose.addView(actions); body.addView(compose);
  TextView hint=label("TEXT MODE  ·  Urdu / Hindi / English  ·  encrypted keys",11); hint.setTextColor(0xff477052); hint.setTypeface(android.graphics.Typeface.MONOSPACE); body.addView(hint);
 }
 void quickMenu(){
  LinearLayout p=panel(); p.setBackgroundColor(0xff09110c); TextView h=label("JARVIS CONTROL",20); h.setTextColor(0xff55ff88); h.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD); p.addView(h);
  p.addView(button("Models & API connections",()->{connections();})); p.addView(button("Project workspace",()->{projectScreen();})); p.addView(button("Generate image",()->{imageDialog();})); p.addView(button("Clear conversation",()->{if(busy){toast("Wait for current reply");return;}new AlertDialog.Builder(this).setMessage("Clear this conversation? Your project stays saved.").setPositiveButton("Clear",(d,w)->{history=new JSONArray();photo="";save();renderHistory();}).setNegativeButton("Cancel",null).show();}));
  new AlertDialog.Builder(this).setView(p).setNegativeButton("Close",null).show();
 }
 void renderHistory(){if(chat==null)return;chat.removeAllViews();for(int i=Math.max(0,history.length()-12);i<history.length();i++){JSONObject m=history.optJSONObject(i);boolean user=m.optString("role").equals("user");TextView t=label(m.optString("content"),16);t.setTextColor(user?0xff07100a:0xffd9ffe2);t.setTextIsSelectable(true);t.setPadding(dp(16),dp(12),dp(16),dp(12));GradientDrawable bg=new GradientDrawable();bg.setColor(user?0xff55ff88:0xff101b13);bg.setStroke(dp(1),user?0xff55ff88:0xff245d35);bg.setCornerRadius(dp(18));t.setBackground(bg);t.setMaxWidth(dp(310));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.gravity=user?Gravity.END:Gravity.START;lp.setMargins(dp(4),dp(7),dp(4),dp(7));chat.addView(t,lp);}}
 void save(){try{Vault.save(this,"history",history.toString());Vault.save(this,"profiles",profiles.toString());getPreferences(0).edit().putInt("selected",selected).apply();}catch(Exception e){toast("Could not save securely");}}
 void send(String text){
  if(busy)return; if(text==null||text.trim().isEmpty()){toast("Message लिखिए फिर Send दबाइए");return;}
  if(selected<0||selected>=profiles.length()){toast("पहले ⋮ → Models → Add API key करें");connections();return;}
  final JSONObject profile=profiles.optJSONObject(selected);if(profile==null||!profile.has("key")||!profile.has("url")||!profile.has("model")||!profile.has("type")){toast("Saved connection अधूरी है। इसे delete करके API key फिर से Connect करें");connections();return;}
  busy=true;input.setText("");status.setText("Thinking…");if(calling&&agentState!=null){agentState.setText("THINKING · Jarvis is working");if(wave!=null)wave.setText("▂ ▆ █ ▆ ▂ ·");}
  final boolean create=mode!=null&&mode.getSelectedItemPosition()==1;final String image=photo;photo="";final String previous=project;
  try{history.put(Ai.obj("role","user","content",text));save();renderHistory();final JSONArray context=new JSONArray(history.toString());pool.execute(()->{try{
    String instruction=system+(create?" Return one COMPLETE HTML document with inline CSS/JS, accessible mobile-first UI, functional controls, no external paid dependencies. Implement the requested changes. Do not output partial patches. Current project: "+previous:"");
    String reply=Ai.ask(profile,context,instruction,image);final String html=create?Ai.html(reply):"";if(create){if(!previous.isEmpty())Fs.writeString(new File(getFilesDir(),"project-previous.html").toPath(),previous);Fs.writeString(new File(getFilesDir(),"project.html").toPath(),html);}
    runOnUiThread(()->{try{busy=false;project=create?html:project;history.put(Ai.obj("role","assistant","content",reply));save();renderHistory();status.setText(create?"Project saved · open Project":"Ready");if(calling){if(agentState!=null)agentState.setText("SPEAKING · Jarvis reply");if(wave!=null)wave.setText("▂ ▄ ▆ █ ▆ ▄ ▂");String spoken=create?"آپ کا ویب ایپ پروجیکٹ تیار ہے۔":reply.replaceAll("(?s)```.*?```","کوڈ پروجیکٹ میں دیکھیں");if(tts!=null)tts.speak(spoken.substring(0,Math.min(spoken.length(),3500)),TextToSpeech.QUEUE_FLUSH,null,"reply");}}catch(Throwable ui){busy=false;showFailure(ui);}});
  }catch(Throwable failure){runOnUiThread(()->{busy=false;showFailure(failure);});}});
  }catch(Throwable failure){busy=false;showFailure(failure);}
 }
 void showFailure(Throwable error){String msg=error.getMessage();if(msg==null||msg.trim().isEmpty())msg=error.getClass().getSimpleName();if(msg.length()>900)msg=msg.substring(0,900);if(calling)stopCall();status.setText("ERROR · "+msg);Toast.makeText(this,"Jarvis request failed. Details are shown above.",Toast.LENGTH_LONG).show();}
 void connections(){if(busy){toast("Wait for current reply before changing model");return;}LinearLayout p=panel();p.addView(label("Your AI connections",23));for(int i=0;i<profiles.length();i++){final int n=i;JSONObject v=profiles.optJSONObject(i);p.addView(button((i==selected?"✓ ":"")+v.optString("name")+" · "+v.optString("model"),()->{selected=n;save();toast("Connection selected");}));}p.addView(button("Add / replace connection",()->editConnection()));p.addView(button("Delete selected connection",()->{if(selected<profiles.length())new AlertDialog.Builder(this).setMessage("Delete this saved key?").setPositiveButton("Delete",(d,w)->{profiles.remove(selected);selected=0;save();}).setNegativeButton("Cancel",null).show();}));p.addView(button("Test selected connection",()->{if(selected>=profiles.length()){toast("Add a connection first");return;}JSONObject v=profiles.optJSONObject(selected);pool.execute(()->{try{Ai.ask(v,new JSONArray().put(Ai.obj("role","user","content","Reply OK")),"Connection test","");toast("Connection works");}catch(Exception e){toast(e.getMessage());}});}));p.addView(label("Switching providers sends the recent conversation and current project to the provider you select. Test calls may consume credits. No automatic paid fallback.",13));ScrollView s=new ScrollView(this);s.addView(p);new AlertDialog.Builder(this).setView(s).setPositiveButton("Done",null).show();}
 void editConnection(){
  LinearLayout p=panel(); TextView help=label("Paste one API key. Jarvis will detect common providers automatically.",14); help.setTextColor(0xff65d98a); p.addView(help);
  EditText key=field("Paste API key here",""); key.setInputType(129); p.addView(key);
  TextView detected=label("Provider: waiting for key",13); detected.setTextColor(0xff86a58d); p.addView(detected);
  key.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){JSONObject d=AutoConnect.detect(s.toString().trim());detected.setText(d.optBoolean("known")?"Detected: "+d.optString("name")+" · "+d.optString("model"):"Provider not recognized · use Advanced setup");}public void afterTextChanged(android.text.Editable e){}});
  p.addView(label("The key is encrypted on this phone. Jarvis detects common keys, chooses a default model and tests the connection automatically.",12));
  p.addView(button("Advanced provider setup",()->new AlertDialog.Builder(this).setMessage("For a custom provider, use the full Base URL, protocol and Model ID. Common keys do not need this.").setPositiveButton("Okay",null).show()));
  ScrollView s=new ScrollView(this);s.addView(p);new AlertDialog.Builder(this).setTitle("Connect AI").setView(s).setPositiveButton("Connect",(d,w)->{try{String raw=key.getText().toString().trim();if(raw.isEmpty())throw new Exception("Paste an API key first");JSONObject v=AutoConnect.detect(raw);if(!v.optBoolean("known"))throw new Exception("This key format is not recognized. Use Advanced setup.");profiles.put(v);selected=profiles.length()-1;save();toast("Connected to "+v.optString("name")+" · testing…");pool.execute(()->{try{Ai.ask(v,new JSONArray().put(Ai.obj("role","user","content","Reply with only: OK")),"Connection test","");toast("Connection works");}catch(Exception e){toast("Saved, but test failed: "+e.getMessage());}});}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("Cancel",null).show();
 }
 void projectScreen(){LinearLayout p=panel();p.addView(label("Your web-app project",23));p.addView(label("Generate a project using Create mode. This build supports HTML/CSS/JS web apps; native Android projects require a separate build implementation.",14));p.addView(button("Preview",()->{try{if(project.isEmpty())throw new Exception("Create a project first");Fs.writeString(new File(getFilesDir(),"preview.html").toPath(),project);startActivity(new Intent(this,PreviewActivity.class));}catch(Exception e){toast(e.getMessage());}}));p.addView(button("Export website HTML",()->{export=project;if(export.isEmpty()){toast("Create a project first");return;}startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/html").putExtra(Intent.EXTRA_TITLE,"index.html").addCategory(Intent.CATEGORY_OPENABLE),21);}));p.addView(button("Restore previous version",()->{try{project=Fs.readString(new File(getFilesDir(),"project-previous.html").toPath());Fs.writeString(new File(getFilesDir(),"project.html").toPath(),project);toast("Previous version restored");}catch(Exception e){toast("No previous version yet");}}));p.addView(button("Build APK on GitHub",()->buildSettings()));p.addView(button("Check APK build",()->checkBuild()));new AlertDialog.Builder(this).setView(p).setPositiveButton("Done",null).show();}
 void startCall(){if(busy){toast("Wait for the current reply");return;}if(!voiceReady){toast("Urdu voice is unavailable. Install an Urdu text-to-speech voice in Android settings.");return;}if(selected>=profiles.length()){connections();return;}if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},50);return;}calling=true;speechErrors=0;if(agentPanel!=null)agentPanel.setVisibility(View.VISIBLE);if(call!=null)call.setText("END");listenLater();}
 void listenLater(){handler.postDelayed(()->{if(!calling||busy||!foreground)return;try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ur-PK").putExtra(RecognizerIntent.EXTRA_LANGUAGE_PREFERENCE,"ur-PK").putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_PROMPT,"Jarvis सुन रहा है…");startActivityForResult(i,30);if(agentState!=null)agentState.setText("LISTENING · Urdu / Hindi");if(wave!=null)wave.setText("▂ ▄ ▆ █ ▆ ▄ ▂");status.setText("Listening… बोलिए");}catch(Exception e){stopCall();toast("Voice input app उपलब्ध नहीं है। Google app / Speech Services install या enable करें।");}},450);}
 void stopCall(){calling=false;handler.removeCallbacksAndMessages(null);if(tts!=null)tts.stop();if(speech!=null){speech.cancel();speech.destroy();speech=null;}if(agentPanel!=null)agentPanel.setVisibility(View.GONE);if(call!=null)call.setText("CALL");if(status!=null&&!busy)status.setText("●  READY");}
 public void onResults(Bundle b){ArrayList<String>r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(calling&&r!=null&&!r.isEmpty()){speechErrors=0;send(r.get(0));}else if(calling)listenLater();}public void onError(int e){if(!calling)return;if((e==SpeechRecognizer.ERROR_NO_MATCH||e==SpeechRecognizer.ERROR_SPEECH_TIMEOUT)&&++speechErrors<4)listenLater();else{stopCall();toast("Voice paused ("+e+"). Check Urdu speech support and connection; tap Start to retry.");}}
 public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){status.setText("Understanding…");}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==50&&g.length>0&&g[0]==0)startCall();}
 protected void onPause(){foreground=false;stopCall();super.onPause();}protected void onResume(){super.onResume();foreground=true;}protected void onDestroy(){stopCall();if(tts!=null)tts.shutdown();pool.shutdown();super.onDestroy();}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==30){if(result==RESULT_OK&&data!=null){ArrayList<String> r=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(calling&&r!=null&&!r.isEmpty()){speechErrors=0;send(r.get(0));}else if(calling)listenLater();}else if(calling){if(++speechErrors<3)listenLater();else{stopCall();toast("Voice input cancelled. Tap CALL to try again.");}}return;}if(result!=RESULT_OK||data==null)return;try{if(request==21){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(export.getBytes(java.nio.charset.StandardCharsets.UTF_8));}toast("Website exported");}if(request==20){android.graphics.ImageDecoder.Source source=android.graphics.ImageDecoder.createSource(getContentResolver(),data.getData());Bitmap bitmap=android.graphics.ImageDecoder.decodeBitmap(source,(decoder,info,src)->{int w=info.getSize().getWidth(),h=info.getSize().getHeight();double scale=Math.min(1,1200.0/Math.max(w,h));decoder.setTargetSize((int)(w*scale),(int)(h*scale));decoder.setAllocator(android.graphics.ImageDecoder.ALLOCATOR_SOFTWARE);});ByteArrayOutputStream out=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.JPEG,85,out);bitmap.recycle();photo=android.util.Base64.encodeToString(out.toByteArray(),2);toast("Photo attached to next message");}}catch(Exception e){toast("Could not open or save file");}}
 void imageDialog(){stopCall();if(selected>=profiles.length()){connections();return;}LinearLayout p=panel();EditText model=field("Image model ID (not chat model)",""),prompt=field("Describe the image","");prompt.setSingleLine(false);p.addView(model);p.addView(prompt);p.addView(label("Uses the selected provider. Requires a supported Gemini image model or an Images-compatible endpoint. Image generation may cost credits. Output will be saved to Gallery.",13));new AlertDialog.Builder(this).setTitle("Create image").setView(p).setPositiveButton("Generate",(d,w)->{JSONObject provider=profiles.optJSONObject(selected);pool.execute(()->{try{Images.create(this,provider,model.getText().toString().trim(),prompt.getText().toString());toast("Image saved to Gallery/Jarvis");}catch(Exception e){toast(e.getMessage());}});}).setNegativeButton("Cancel",null).show();}
 void buildSettings(){if(project.isEmpty()){toast("Create a project first");return;}try{LinearLayout p=panel();EditText repo=field("owner/repository",Vault.get(this,"repo","mazharmnzoor4227-beep/universal-build-studio")),token=field("GitHub token",Vault.get(this,"github","")),name=field("App name","My App"),pkg=field("Package ID","com.mazhar.myapp");token.setInputType(129);p.addView(repo);p.addView(token);p.addView(name);p.addView(pkg);p.addView(label("Requires jarvis-project.yml in this repository and a GitHub token with Actions read/write. Sends this HTML to your GitHub build runner; Actions minutes/storage limits apply. Output is a debug-signed web app.",13));new AlertDialog.Builder(this).setTitle("Build web app APK").setView(p).setPositiveButton("Build",(d,w)->{try{String r=repo.getText().toString().trim(),t=token.getText().toString().trim(),n=name.getText().toString(),id=pkg.getText().toString();Vault.save(this,"repo",r);Vault.save(this,"github",t);String html=project;pool.execute(()->{try{String ticket=GitBuild.start(r,t,n,id,html);getPreferences(0).edit().putString("buildTicket",ticket).apply();toast("Build started. Use Check APK build to download when ready.");}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("Cancel",null).show();}catch(Exception e){toast("Could not load build settings");}}
 void checkBuild(){pool.execute(()->{try{String ticket=getPreferences(0).getString("buildTicket","");if(ticket.isEmpty())throw new Exception("Start a build first");GitBuild.check(this,Vault.get(this,"repo",""),Vault.get(this,"github",""),ticket);toast("APK saved to Downloads/Jarvis");}catch(Exception e){toast(e.getMessage());}});}
}
