package com.mazhar.jarvis;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.speech.*;import android.speech.tts.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.file.Files;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity implements RecognitionListener {
 final ExecutorService pool=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());
 JSONArray profiles=new JSONArray(),history=new JSONArray();int selected=0;boolean busy=false,calling=false,voiceReady=false,foreground=true;int speechErrors=0;
 SpeechRecognizer speech;TextToSpeech tts;LinearLayout body,chat;TextView status;EditText input;Button call;Spinner mode;String photo="",project="";String export="";
 final String system="You are Jarvis, an AI work assistant. Speak concise natural Urdu by default; use English for code and listing copy. Do not claim to be human or to have completed tool actions you cannot perform. User runs Clawora Beauty, a cosmetics reseller. Do not invent product ingredients, safety claims, official images or verified facts. Ask for missing details. Never claim an APK was built or a website published by writing text. Your tools here are generating text and a complete self-contained HTML/CSS/JS file for a web-app project. No live web search or Shopify access is connected. Respect privacy and refuse harmful requests.";
 @Override public void onCreate(Bundle state){super.onCreate(state);try{profiles=new JSONArray(Vault.get(this,"profiles","[]"));history=new JSONArray(Vault.get(this,"history","[]"));selected=getPreferences(0).getInt("selected",0);File f=new File(getFilesDir(),"project.html");if(f.exists())project=Fs.readString(f.toPath());}catch(Exception e){toast("Could not restore saved data: "+e.getMessage());}
 tts=new TextToSpeech(this,result->{if(result==TextToSpeech.SUCCESS){int lang=tts.setLanguage(Locale.forLanguageTag("ur-PK"));voiceReady=lang>=0;if(!voiceReady)toast("Install an Urdu text-to-speech voice in Android settings for spoken replies.");}});
 tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){handler.post(()->{if(calling)listenLater();});}public void onError(String id){handler.post(()->{stopCall();toast("Speech playback failed; check Urdu voice settings");});}});
 home();}
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
 void toast(String s){runOnUiThread(()->{if(status!=null)status.setText(s);Toast.makeText(this,s,Toast.LENGTH_LONG).show();});}
 TextView label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(0xffeeeeef);t.setPadding(0,dp(8),0,dp(8));return t;}
 Button button(String text,Runnable action){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(0xff141419);GradientDrawable bg=new GradientDrawable();bg.setColor(0xffefeff4);bg.setCornerRadius(dp(18));b.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(lp);b.setOnClickListener(v->action.run());return b;}
 EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(-1);e.setHintTextColor(0xffaaaab3);e.setSingleLine(true);e.setPadding(dp(10),dp(8),dp(10),dp(8));return e;}
 LinearLayout panel(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(dp(20),dp(12),dp(20),dp(12));return l;}
 void home(){ScrollView scroll=new ScrollView(this);body=panel();body.setBackgroundColor(0xff111216);scroll.addView(body);scroll.setFillViewport(true);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom);return insets;});
 body.addView(label("J A R V I S",30));body.addView(label("Speak. Create. Keep building.",15));status=label("Ready · your projects stay on this device",13);body.addView(status);
 LinearLayout bar=new LinearLayout(this);Button models=button("Models",()->{stopCall();connections();}),projects=button("Project",()->{stopCall();projectScreen();});bar.addView(models,new LinearLayout.LayoutParams(0,dp(48),1));bar.addView(projects,new LinearLayout.LayoutParams(0,dp(48),1));body.addView(bar);
 mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Chat / product listing","Create or edit website / web app"}));body.addView(mode);
 call=button("Start Urdu call",()->{if(calling){stopCall();}else startCall();});body.addView(call);body.addView(button("Interrupt reply",()->{tts.stop();if(calling&&!busy)listenLater();}));
 chat=panel();body.addView(chat);renderHistory();input=field("Type or speak your request…","");input.setSingleLine(false);input.setMinLines(2);body.addView(input);body.addView(button("Attach product photo",()->{stopCall();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,20);}));body.addView(button("Send",()->send(input.getText().toString())));body.addView(button("Generate image",()->imageDialog()));body.addView(button("New conversation",()->{if(busy){toast("Wait for the current reply");return;}stopCall();new AlertDialog.Builder(this).setMessage("Clear this conversation? Your project is kept.").setPositiveButton("Clear",(d,w)->{history=new JSONArray();photo="";save();renderHistory();}).setNegativeButton("Cancel",null).show();}));body.addView(label("Voice is active while this screen is open. Free-model limits depend on your provider. Keys are encrypted on this device.",12));}
 void renderHistory(){if(chat==null)return;chat.removeAllViews();for(int i=Math.max(0,history.length()-8);i<history.length();i++){JSONObject m=history.optJSONObject(i);TextView t=label((m.optString("role").equals("user")?"YOU\n":"JARVIS\n")+m.optString("content"),16);t.setTextIsSelectable(true);chat.addView(t);}}
 void save(){try{Vault.save(this,"history",history.toString());Vault.save(this,"profiles",profiles.toString());getPreferences(0).edit().putInt("selected",selected).apply();}catch(Exception e){toast("Could not save securely");}}
 void send(String text){if(busy||text.trim().isEmpty())return;if(selected>=profiles.length()){stopCall();connections();return;}busy=true;input.setText("");status.setText("Thinking…");final boolean create=mode.getSelectedItemPosition()==1;final String image=photo;photo="";final JSONObject profile=profiles.optJSONObject(selected);final String previous=project;
 try{history.put(Ai.obj("role","user","content",text));save();renderHistory();final JSONArray context=new JSONArray(history.toString());pool.execute(()->{try{String instruction=system+(create?" Return one COMPLETE HTML document with inline CSS/JS, accessible mobile-first UI, functional controls, no external paid dependencies. Implement the requested changes. Do not output partial patches. Current project: "+previous:"");String reply=Ai.ask(profile,context,instruction,image);final String html=create?Ai.html(reply):"";if(create){if(!previous.isEmpty())Fs.writeString(new File(getFilesDir(),"project-previous.html").toPath(),previous);Fs.writeString(new File(getFilesDir(),"project.html").toPath(),html);}runOnUiThread(()->{busy=false;project=create?html:project;try{history.put(Ai.obj("role","assistant","content",reply));save();renderHistory();status.setText(create?"Project saved · open Project to preview or build APK":"Ready");if(calling){String spoken=create?"آپ کا ویب ایپ پروجیکٹ تیار ہے۔ پروجیکٹ کھول کر پریویو دیکھ سکتے ہیں۔":reply.replaceAll("(?s)```.*?```","کوڈ پروجیکٹ میں دیکھیں");tts.speak(spoken.substring(0,Math.min(spoken.length(),3500)),TextToSpeech.QUEUE_FLUSH,null,"reply");}}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{busy=false;stopCall();toast(e.getMessage()+" Your conversation is saved. Select another model and try again.");});}});}catch(Exception e){busy=false;toast(e.getMessage());}}
 void connections(){if(busy){toast("Wait for current reply before changing model");return;}LinearLayout p=panel();p.addView(label("Your AI connections",23));for(int i=0;i<profiles.length();i++){final int n=i;JSONObject v=profiles.optJSONObject(i);p.addView(button((i==selected?"✓ ":"")+v.optString("name")+" · "+v.optString("model"),()->{selected=n;save();toast("Connection selected");}));}p.addView(button("Add / replace connection",()->editConnection()));p.addView(button("Delete selected connection",()->{if(selected<profiles.length())new AlertDialog.Builder(this).setMessage("Delete this saved key?").setPositiveButton("Delete",(d,w)->{profiles.remove(selected);selected=0;save();}).setNegativeButton("Cancel",null).show();}));p.addView(button("Test selected connection",()->{if(selected>=profiles.length()){toast("Add a connection first");return;}JSONObject v=profiles.optJSONObject(selected);pool.execute(()->{try{Ai.ask(v,new JSONArray().put(Ai.obj("role","user","content","Reply OK")),"Connection test","");toast("Connection works");}catch(Exception e){toast(e.getMessage());}});}));p.addView(label("Switching providers sends the recent conversation and current project to the provider you select. Test calls may consume credits. No automatic paid fallback.",13));ScrollView s=new ScrollView(this);s.addView(p);new AlertDialog.Builder(this).setView(s).setPositiveButton("Done",null).show();}
 void editConnection(){LinearLayout p=panel();Spinner preset=new Spinner(this);String[] names={"OpenCode Zen","OpenAI","Gemini","Groq","Grok / xAI","OpenRouter","Custom"};preset.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));p.addView(preset);EditText name=field("Connection name",""),url=field("Base URL", ""),key=field("API key",""),model=field("Model ID from provider","");key.setInputType(129);Spinner type=new Spinner(this);String[] protocols={"chat","responses","messages","gemini"};type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,protocols));p.addView(name);p.addView(url);p.addView(key);p.addView(model);p.addView(label("API protocol (must match your model)",13));p.addView(type);
 preset.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>a){}public void onItemSelected(android.widget.AdapterView<?>a,View v,int i,long id){name.setText(names[i]);url.setText(new String[]{"https://opencode.ai/zen/v1","https://api.openai.com/v1","https://generativelanguage.googleapis.com/v1beta","https://api.groq.com/openai/v1","https://api.x.ai/v1","https://openrouter.ai/api/v1","https://"}[i]);type.setSelection(i==2?3:i==1||i==4?1:0);}});
 p.addView(label("OpenCode: the protocol depends on the model. Use its documented Model ID. Image and voice availability vary; a key does not unlock every capability.",13));ScrollView s=new ScrollView(this);s.addView(p);new AlertDialog.Builder(this).setTitle("Add API connection").setView(s).setPositiveButton("Save",(d,w)->{try{JSONObject v=Ai.obj("name",name.getText().toString(),"url",url.getText().toString().trim(),"key",key.getText().toString().trim(),"model",model.getText().toString().trim(),"type",protocols[type.getSelectedItemPosition()]);Ai.endpoint(v);if(v.getString("key").isEmpty()||v.getString("model").isEmpty())throw new Exception("Key and model ID are required");profiles.put(v);selected=profiles.length()-1;save();toast("Connection saved");}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("Cancel",null).show();}
 void projectScreen(){LinearLayout p=panel();p.addView(label("Your web-app project",23));p.addView(label("Generate a project using Create mode. This build supports HTML/CSS/JS web apps; native Android projects require a separate build implementation.",14));p.addView(button("Preview",()->{try{if(project.isEmpty())throw new Exception("Create a project first");Fs.writeString(new File(getFilesDir(),"preview.html").toPath(),project);startActivity(new Intent(this,PreviewActivity.class));}catch(Exception e){toast(e.getMessage());}}));p.addView(button("Export website HTML",()->{export=project;if(export.isEmpty()){toast("Create a project first");return;}startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/html").putExtra(Intent.EXTRA_TITLE,"index.html").addCategory(Intent.CATEGORY_OPENABLE),21);}));p.addView(button("Restore previous version",()->{try{project=Fs.readString(new File(getFilesDir(),"project-previous.html").toPath());Fs.writeString(new File(getFilesDir(),"project.html").toPath(),project);toast("Previous version restored");}catch(Exception e){toast("No previous version yet");}}));p.addView(button("Build APK on GitHub",()->buildSettings()));p.addView(button("Check APK build",()->checkBuild()));new AlertDialog.Builder(this).setView(p).setPositiveButton("Done",null).show();}
 void startCall(){if(busy){toast("Wait for the reply first");return;}if(!voiceReady){toast("Urdu voice unavailable. Install an Urdu voice under Android text-to-speech settings.");return;}if(selected>=profiles.length()){connections();return;}if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},50);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Install or enable an Android speech recognition service");return;}calling=true;speechErrors=0;call.setText("End call");listenLater();}
 void listenLater(){handler.postDelayed(()->{if(!calling||busy||!foreground)return;try{if(speech!=null)speech.destroy();speech=SpeechRecognizer.createSpeechRecognizer(this);speech.setRecognitionListener(this);Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ur-PK").putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);speech.startListening(i);status.setText("Listening · Urdu");}catch(Exception e){stopCall();toast("Speech recognition could not start");}},600);}
 void stopCall(){calling=false;handler.removeCallbacksAndMessages(null);if(tts!=null)tts.stop();if(speech!=null){speech.cancel();speech.destroy();speech=null;}if(call!=null)call.setText("Start Urdu call");}
 public void onResults(Bundle b){ArrayList<String>r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(calling&&r!=null&&!r.isEmpty()){speechErrors=0;send(r.get(0));}else if(calling)listenLater();}public void onError(int e){if(!calling)return;if((e==SpeechRecognizer.ERROR_NO_MATCH||e==SpeechRecognizer.ERROR_SPEECH_TIMEOUT)&&++speechErrors<4)listenLater();else{stopCall();toast("Voice paused ("+e+"). Check Urdu speech support and connection; tap Start to retry.");}}
 public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){status.setText("Understanding…");}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==50&&g.length>0&&g[0]==0)startCall();}
 protected void onPause(){foreground=false;stopCall();super.onPause();}protected void onResume(){super.onResume();foreground=true;}protected void onDestroy(){stopCall();if(tts!=null)tts.shutdown();pool.shutdown();super.onDestroy();}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;try{if(request==21){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(export.getBytes(java.nio.charset.StandardCharsets.UTF_8));}toast("Website exported");}if(request==20){android.graphics.ImageDecoder.Source source=android.graphics.ImageDecoder.createSource(getContentResolver(),data.getData());Bitmap bitmap=android.graphics.ImageDecoder.decodeBitmap(source,(decoder,info,src)->{int w=info.getSize().getWidth(),h=info.getSize().getHeight();double scale=Math.min(1,1200.0/Math.max(w,h));decoder.setTargetSize((int)(w*scale),(int)(h*scale));decoder.setAllocator(android.graphics.ImageDecoder.ALLOCATOR_SOFTWARE);});ByteArrayOutputStream out=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.JPEG,85,out);bitmap.recycle();photo=android.util.Base64.encodeToString(out.toByteArray(),2);toast("Photo attached to next message · choose a vision-capable model");}}catch(Exception e){toast("Could not open or save file");}}
 void imageDialog(){stopCall();if(selected>=profiles.length()){connections();return;}LinearLayout p=panel();EditText model=field("Image model ID (not chat model)",""),prompt=field("Describe the image","");prompt.setSingleLine(false);p.addView(model);p.addView(prompt);p.addView(label("Uses the selected provider. Requires a supported Gemini image model or an Images-compatible endpoint. Image generation may cost credits. Output will be saved to Gallery.",13));new AlertDialog.Builder(this).setTitle("Create image").setView(p).setPositiveButton("Generate",(d,w)->{JSONObject provider=profiles.optJSONObject(selected);pool.execute(()->{try{Images.create(this,provider,model.getText().toString().trim(),prompt.getText().toString());toast("Image saved to Gallery/Jarvis");}catch(Exception e){toast(e.getMessage());}});}).setNegativeButton("Cancel",null).show();}
 void buildSettings(){if(project.isEmpty()){toast("Create a project first");return;}try{LinearLayout p=panel();EditText repo=field("owner/repository",Vault.get(this,"repo","mazharmnzoor4227-beep/universal-build-studio")),token=field("GitHub token",Vault.get(this,"github","")),name=field("App name","My App"),pkg=field("Package ID","com.mazhar.myapp");token.setInputType(129);p.addView(repo);p.addView(token);p.addView(name);p.addView(pkg);p.addView(label("Requires jarvis-project.yml in this repository and a GitHub token with Actions read/write. Sends this HTML to your GitHub build runner; Actions minutes/storage limits apply. Output is a debug-signed web app.",13));new AlertDialog.Builder(this).setTitle("Build web app APK").setView(p).setPositiveButton("Build",(d,w)->{try{String r=repo.getText().toString().trim(),t=token.getText().toString().trim(),n=name.getText().toString(),id=pkg.getText().toString();Vault.save(this,"repo",r);Vault.save(this,"github",t);String html=project;pool.execute(()->{try{String ticket=GitBuild.start(r,t,n,id,html);getPreferences(0).edit().putString("buildTicket",ticket).apply();toast("Build started. Use Check APK build to download when ready.");}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("Cancel",null).show();}catch(Exception e){toast("Could not load build settings");}}
 void checkBuild(){pool.execute(()->{try{String ticket=getPreferences(0).getString("buildTicket","");if(ticket.isEmpty())throw new Exception("Start a build first");GitBuild.check(this,Vault.get(this,"repo",""),Vault.get(this,"github",""),ticket);toast("APK saved to Downloads/Jarvis");}catch(Exception e){toast(e.getMessage());}});}
}
