package com.mazhar.cybercore;
import android.view.WindowInsets;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.speech.*;import android.speech.tts.*;import android.webkit.*;import android.provider.MediaStore;import androidx.webkit.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity implements RecognitionListener {
 WebView web;SpeechRecognizer recognizer;TextToSpeech tts;boolean ttsReady=false,permissionDialog=false,voiceDialog=false,foreground=true;String language="ur-PK",speakingId="";int session=0;final Handler main=new Handler(Looper.getMainLooper());
 static final String ORIGIN="https://appassets.androidplatform.net";
 public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);web.setBackgroundColor(0xff020604);web.setOnApplyWindowInsetsListener((v,i)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=i.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(x.left,x.top,x.right,x.bottom);}else{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());}return i;});web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.setWebChromeClient(new WebChromeClient(){public boolean onJsConfirm(WebView v,String u,String m,JsResult r){new AlertDialog.Builder(MainActivity.this).setMessage(m).setPositiveButton("Continue",(d,w)->r.confirm()).setNegativeButton("Cancel",(d,w)->r.cancel()).setOnCancelListener(d->r.cancel()).show();return true;}});
 WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();web.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(!r.isForMainFrame())return false;String u=r.getUrl().toString();if(u.equals(ORIGIN+"/assets/index.html"))return false;if(u.startsWith("https://"))try{startActivity(new Intent(Intent.ACTION_VIEW,r.getUrl()));}catch(Exception e){notice("No browser is available to open this link.");}return true;}});
 if(WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)){WebViewCompat.addWebMessageListener(web,"NativeVoice",Collections.singleton(ORIGIN),(view,message,source,isMainFrame,reply)->{if(!isMainFrame||!ORIGIN.equals(source.toString()))return;try{JSONObject j=new JSONObject(message.getData());switch(j.optString("action")){case "http":http(j);break;case "cancelHttp":java.net.HttpURLConnection c=connections.remove(j.optInt("id"));if(c!=null)new Thread(c::disconnect).start();break;case "start":language=j.optString("lang","ur-PK");session=j.optInt("session");startListening();break;case "stop":stopListening();break;case "speak":say(j.optString("text"));break;case "cancelSpeech":if(tts!=null)tts.stop();speakingId="";break;case "save":saveText(j);break;case "ready":emit("ready",ttsReady?"available":"pending");break;}}catch(Exception e){notice("Native request failed: "+e.getClass().getSimpleName());}});}
 tts=new TextToSpeech(this,status->{ttsReady=status==TextToSpeech.SUCCESS;emit("ready",ttsReady?"available":"unavailable");});tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){if(id.equals(speakingId))emit("speechEnd","");}public void onError(String id){emit("speechError","Urdu speech playback failed");}});
 web.loadUrl(ORIGIN+"/assets/index.html");}

 final java.util.concurrent.ConcurrentHashMap<Integer,java.net.HttpURLConnection> connections=new java.util.concurrent.ConcurrentHashMap<>();
 void http(JSONObject j){new Thread(()->{int id=j.optInt("id");JSONObject out=new JSONObject();java.net.HttpURLConnection c=null;try{out.put("event","http").put("id",id);java.net.URL u=new java.net.URL(j.getString("url"));if(!u.getProtocol().equals("https")||u.getUserInfo()!=null||(u.getPort()!=-1&&u.getPort()!=443)||!Arrays.asList("generativelanguage.googleapis.com","api.openai.com","openrouter.ai","api.github.com").contains(u.getHost()))throw new Exception("Endpoint is not allowed");String method=j.optString("method","GET");if(!Arrays.asList("GET","POST","PATCH").contains(method))throw new Exception("Method is not allowed");c=(java.net.HttpURLConnection)u.openConnection();connections.put(id,c);c.setInstanceFollowRedirects(false);c.setRequestMethod(method);c.setConnectTimeout(20000);c.setReadTimeout(110000);JSONObject headers=j.optJSONObject("headers");if(headers!=null){Iterator<String> it=headers.keys();while(it.hasNext()){String k=it.next();if(Arrays.asList("accept","content-type","authorization","x-goog-api-key").contains(k.toLowerCase(Locale.ROOT)))c.setRequestProperty(k,headers.getString(k));}}String body=j.optString("body");if(!body.isEmpty()){c.setDoOutput(true);try(java.io.OutputStream stream=c.getOutputStream()){stream.write(body.getBytes(java.nio.charset.StandardCharsets.UTF_8));}}int status=c.getResponseCode();java.io.InputStream input=status>=400?c.getErrorStream():c.getInputStream();java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();if(input!=null)try(java.io.InputStream stream=input){byte[] buffer=new byte[8192];int n;while((n=stream.read(buffer))!=-1){if(bytes.size()+n>10000000)throw new Exception("Response too large");bytes.write(buffer,0,n);}}out.put("status",status).put("body",bytes.toString("UTF-8"));}catch(Exception e){try{out.put("error","Network request failed ("+e.getClass().getSimpleName()+"). Check internet or retry.");}catch(Exception ignored){}}finally{connections.remove(id);if(c!=null)c.disconnect();}main.post(()->{if(web!=null)web.evaluateJavascript("window.cyberNativeEvent && window.cyberNativeEvent("+out.toString()+")",null);});}).start();}

 void emit(String event,String text){int id=session;main.post(()->{if(web!=null){JSONObject data=new JSONObject();try{data.put("event",event).put("text",text).put("session",id);}catch(Exception ignored){}web.evaluateJavascript("window.cyberNativeEvent && window.cyberNativeEvent("+data.toString()+")",null);}});}
 void notice(String t){emit("notice",t);}
 void startListening(){if(!foreground)return;if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){permissionDialog=true;requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},77);return;}stopListening();if(SpeechRecognizer.isRecognitionAvailable(this)){recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(this);try{recognizer.startListening(recognitionIntent());}catch(Exception e){fallback();}}else fallback();}
 Intent recognitionIntent(){return new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE,language).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);}
 void fallback(){stopListening();try{voiceDialog=true;startActivityForResult(recognitionIntent().putExtra(RecognizerIntent.EXTRA_PROMPT,"Speak to Cyber Core"),78);}catch(Exception e){voiceDialog=false;emit("error","service-not-available");}}
 void stopListening(){if(recognizer!=null){recognizer.cancel();recognizer.destroy();recognizer=null;}}
 void say(String text){if(!ttsReady){emit("speechError","Text-to-speech is not ready. Try again shortly.");return;}int supported=tts.setLanguage(Locale.forLanguageTag("ur-PK"));if(supported<0){emit("speechError","No Urdu voice installed. Install an Urdu system voice; text chat still works.");return;}speakingId=UUID.randomUUID().toString();int max=TextToSpeech.getMaxSpeechInputLength();if(text.length()>max){emit("speechError","Reply is too long for this voice. Ask for a shorter spoken answer.");return;}tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,speakingId);}
 void saveText(JSONObject j)throws Exception{String name=j.optString("name","export.txt").replaceAll("[^a-zA-Z0-9._-]","_");String body=j.optString("body");if(body.length()>5000000)throw new Exception("Export too large");ContentValues v=new ContentValues();v.put(MediaStore.MediaColumns.DISPLAY_NAME,name);v.put(MediaStore.MediaColumns.MIME_TYPE,j.optString("type","text/plain"));v.put(MediaStore.MediaColumns.RELATIVE_PATH,"Download/CyberCore");v.put(MediaStore.MediaColumns.IS_PENDING,1);Uri uri=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(uri==null)throw new Exception("Cannot save");try{try(java.io.OutputStream out=getContentResolver().openOutputStream(uri)){out.write(body.getBytes(java.nio.charset.StandardCharsets.UTF_8));}v.clear();v.put(MediaStore.MediaColumns.IS_PENDING,0);getContentResolver().update(uri,v,null,null);notice("Saved in Downloads/CyberCore: "+name);}catch(Exception e){getContentResolver().delete(uri,null,null);throw e;}}
 public void onReadyForSpeech(Bundle b){emit("start","");}public void onBeginningOfSpeech(){}public void onRmsChanged(float v){emit("volume",String.valueOf(Math.max(0,Math.min(1,(v+2)/12))));}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);emit("result",a!=null&&!a.isEmpty()?a.get(0):"");}public void onPartialResults(Bundle b){ArrayList<String>a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(a!=null&&!a.isEmpty())emit("partial",a.get(0));}public void onEvent(int t,Bundle b){}public void onError(int e){emit("error",e==SpeechRecognizer.ERROR_NO_MATCH||e==SpeechRecognizer.ERROR_SPEECH_TIMEOUT?"no-speech":e==SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS?"not-allowed":e==12||e==13?"language-not-supported":"recognition-error-"+e);}
 public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==77){permissionDialog=false;if(g.length>0&&g[0]==0)startListening();else emit("error","not-allowed");}}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==78){voiceDialog=false;foreground=true;if(result==RESULT_OK&&data!=null){ArrayList<String>a=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);emit("result",a!=null&&!a.isEmpty()?a.get(0):"");}else emit("error","no-speech");}}
 protected void onPause(){super.onPause();foreground=false;if(!voiceDialog&&!permissionDialog){stopListening();if(tts!=null)tts.stop();web.evaluateJavascript("if(window.endCall)endCall()",null);}}
 protected void onResume(){super.onResume();foreground=true;}
 public void onBackPressed(){web.evaluateJavascript("if(S.call){endCall()}else if(document.querySelector('dialog[open]')){document.querySelector('dialog[open]').close()}else{switchTab(false)}",null);}
 protected void onDestroy(){for(java.net.HttpURLConnection c:connections.values())new Thread(c::disconnect).start();connections.clear();stopListening();if(tts!=null)tts.shutdown();if(web!=null){web.destroy();web=null;}super.onDestroy();}
}

